### ISSUE TITLE
End Screen

### ISSUE THREAD

**Issue by Rayneus** [Rayneus/Use-Your-Brain#3]
This obviously is a bit more complicated than the start screen. This is likely best implemented with some sort of popup window the notify the user the game has ended. There should be two screens, one for completion and one for failing (i.e. falling into a pit). There also needs to be the option to return to the start screen, which obviously requires a start screen. Again, a popup window is likely easiest, but you can do a whole screen if you would like.

**Comment by bakabea5t** [comment]
I have fully implemented a simple end screen. and have all commits on the end-screen branch as of 3/28/24.
